__version__ = "1.4.0"

from curricularanalytics.CurricularAnalytics import basic_statistics, homology
from curricularanalytics.DataHandler import read_csv, write_csv
from curricularanalytics.DataTypes.Course import (
    AbstractCourse,
    Course,
    CourseCollection,
    course_id,
)
from curricularanalytics.DataTypes.CourseCatalog import CourseCatalog
from curricularanalytics.DataTypes.Curriculum import Curriculum
from curricularanalytics.DataTypes.DataTypes import (
    EdgeClass,
    Requisite,
    System,
    back_edge,
    co,
    cross_edge,
    forward_edge,
    pre,
    quarter,
    semester,
    strict_co,
    tree_edge,
)
from curricularanalytics.DataTypes.DegreePlan import DegreePlan, Term
from curricularanalytics.DataTypes.DegreeRequirements import (
    AbstractRequirement,
    CourseSet,
    Grade,
    RequirementSet,
    grade,
)
from curricularanalytics.DataTypes.LearningOutcome import LearningOutcome
from curricularanalytics.DataTypes.Simulation import Simulation
from curricularanalytics.DataTypes.Student import Student, simple_students
from curricularanalytics.DataTypes.StudentRecord import CourseRecord, StudentRecord
from curricularanalytics.DataTypes.TransferArticulation import TransferArticulation
from curricularanalytics.DegreePlanAnalytics import basic_metrics, requisite_distance
from curricularanalytics.DegreePlanCreation import bin_filling, create_degree_plan
from curricularanalytics.GraphAlgs import (
    all_paths,
    dfs,
    gad,
    longest_path,
    longest_paths,
    reach,
    reach_subgraph,
    reachable_from,
    reachable_from_subgraph,
    reachable_to,
    reachable_to_subgraph,
    topological_sort,
)

# print(
#     AA,
#     AAS,
#     AS,
#     AbstractCourse,
#     AbstractRequirement,
#     BA,
#     BS,
#     Course,
#     CourseCollection,
#     CourseCatalog,
#     CourseRecord,
#     CourseSet,
#     Curriculum,
#     DegreePlan,
#     EdgeClass,
#     Enrollment,
#     Grade,
#     LearningOutcome,
#     PassRate,
#     RequirementSet,
#     Requisite,
#     Student,
#     StudentRecord,
#     Simulation,
#     System,
#     Term,
#     TransferArticulation,
#     add_course,
#     add_lo_requisite,
#     add_requisite,
#     add_transfer_catalog,
#     add_transfer_course,
#     all_paths,
#     back_edge,
#     basic_metrics,
#     basic_statistics,
#     bin_filling,
#     blocking_factor,
#     centrality,
#     co,
#     compare_curricula,
#     convert_ids,
#     complexity,
#     course,
#     course_from_id,
#     course_from_vertex,
#     course_id,
#     courses_from_vertices,
#     create_degree_plan,
#     cross_edge,
#     dead_ends,
#     delay_factor,
#     delete_requisite,
#     dfs,
#     extraneous_requisites,
#     find_term,
#     forward_edge,
#     gad,
#     grade,
#     homology,
#     is_duplicate,
#     isvalid_curriculum,
#     isvalid_degree_plan,
#     longest_path,
#     longest_paths,
#     merge_curricula,
#     pass_table,
#     passrate_table,
#     pre,
#     print_plan,
#     quarter,
#     reach,
#     reach_subgraph,
#     reachable_from,
#     reachable_from_subgraph,
#     reachable_to,
#     reachable_to_subgraph,
#     read_csv,
#     requisite_distance,
#     requisite_type,
#     semester,
#     set_passrates,
#     set_passrate_for_course,
#     set_passrates_from_csv,
#     similarity,
#     simple_students,
#     simulate,
#     simulation_report,
#     strict_co,
#     topological_sort,
#     total_credits,
#     transfer_equiv,
#     tree_edge,
#     write_csv,
#     knowledge_transfer,
#     csv_stream,
# )
